// ─────────────────────────────────────────────
// Suggested next questions
// ─────────────────────────────────────────────
// Generated by a SEPARATE call, not by appending "…and then list three
// follow-up questions" to the answer prompt. The codebase already learned that
// lesson once: a trailing formatting instruction was "routinely skipped by small
// models", which is why the general-knowledge disclosure line had to become
// deterministic. A tail instruction that a model ignores half the time produces
// a feature that works half the time.
//
// A separate call also keeps the suggestions OUT of the answer. Appended, they
// would be saved into the transcript, fed back as history, cited, and read aloud
// by a screen reader as part of the reply.

/** Branches worth suggesting from — the ones that answered a real question. */
const SUBSTANTIVE = new Set(['citation', 'page', 'web', 'general']);

/**
 * Whether this turn should spend a call on suggestions.
 *
 * Skipped for greetings and questions about the assistant itself (there is no
 * next question), for the no-page branch (the answer is an instruction to
 * attach a page), and for slash commands — a command turn has its own shape and
 * its own follow-up, which is running the command again with different input.
 */
export function shouldSuggestFollowUps(branch: string, hasOverride: boolean): boolean {
  return !hasOverride && SUBSTANTIVE.has(branch);
}

const MAX_SUGGESTIONS = 3;
const MAX_CHARS = 90;

/**
 * Parse the suggestion call's output.
 *
 * Tolerant of everything models do to a "one per line" instruction: numbering,
 * bullets, code fences, a preamble, quotes, bold. Anything that survives is a
 * plausible question; anything that doesn't is dropped rather than shown, since
 * a malformed chip is worse than no chip.
 */
export function parseFollowUps(raw: string): string[] {
  const text = (raw || '')
    // Strip fences; models wrap lists in them unprompted.
    .replace(/```[a-z]*\n?/gi, '')
    .replace(/```/g, '');

  const out: string[] = [];
  const seen = new Set<string>();

  for (let line of text.split('\n')) {
    line = line.trim()
      .replace(/^\d+[.)]\s*/, '')        // "1. " / "1) "
      .replace(/^[-*+•]\s*/, '')         // bullets
      .replace(/^["'“”‘’]|["'“”‘’]$/g, '')
      .replace(/\*\*/g, '')
      .trim();
    if (!line) continue;
    // A preamble ("Here are three questions:") is not a question.
    if (!line.includes('?')) continue;
    // Keep only up to the first question mark: models append explanations.
    line = line.slice(0, line.indexOf('?') + 1).trim();
    if (line.length < 8 || line.length > MAX_CHARS) continue;
    const key = line.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(line);
    if (out.length >= MAX_SUGGESTIONS) break;
  }
  return out;
}

/** The prompt for the suggestion call. Deliberately tiny — this must stay cheap. */
export const FOLLOW_UP_PROMPT =
  `Given the exchange below, write up to 3 short follow-up questions the user would plausibly ask next. ` +
  `Rules: one question per line, nothing else — no numbering, no preamble, no explanation. ` +
  `Each must be under 90 characters, end with a question mark, and be answerable from the same subject. ` +
  `Write them in the SAME LANGUAGE as the user's question. ` +
  `Do not repeat what the answer already covered.`;
